<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Services\Registration\EventFlow.Registration.Application\EventFlow.Registration.Application.csproj" />
		<ProjectReference Include="..\..\src\Services\Registration\EventFlow.Registration.Infrastructure\EventFlow.Registration.Infrastructure.csproj" />
	</ItemGroup>

</Project>
