# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore src/Services/Identity/EventFlow.Identity.Api/EventFlow.Identity.Api.csproj

RUN dotnet publish src/Services/Identity/EventFlow.Identity.Api/EventFlow.Identity.Api.csproj -c Release -o /app/publish --no-restore


# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "EventFlow.Identity.Api.dll"]