# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore src/Gateway/EventFlow.Gateway/EventFlow.Gateway.csproj

RUN dotnet publish src/Gateway/EventFlow.Gateway/EventFlow.Gateway.csproj -c Release -o /app/publish --no-restore


# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "EventFlow.Gateway.dll"]