<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>40a306f0-0c6a-4448-8009-72286ddbeea3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	  <PackageReference Include="Swashbuckle.AspNetCore" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventFlow.Event.Application\EventFlow.Event.Application.csproj" />
    <ProjectReference Include="..\EventFlow.Event.Infrastructure\EventFlow.Event.Infrastructure.csproj" />
  </ItemGroup>

</Project>
