<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\EventFlow.Operations.Application\EventFlow.Operations.Application.csproj" />
		<ProjectReference Include="..\EventFlow.Operations.Domain\EventFlow.Operations.Domain.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\EventFlow.Messaging\EventFlow.Messaging.csproj" />

		<ProjectReference Include="..\..\..\BuildingBlocks\EventFlow.Contracts\EventFlow.Contracts.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\EventFlow.Security\EventFlow.Security.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="MailKit" />
	</ItemGroup>

</Project>