<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b8f2fa5e-0d89-4e68-9b7b-70eac0bbd5dc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventFlow.Operations.Application\EventFlow.Operations.Application.csproj" />
    <ProjectReference Include="..\EventFlow.Operations.Infrastructure\EventFlow.Operations.Infrastructure.csproj" />
  </ItemGroup>

</Project>
